# Estimate object types for a cluster of bounding boxes  

# relevant object types
string[] type 

# unique object identifiers
string[] object_id

# poses
geometry_msgs/Pose[] pose

# local bounding boxes
strands_qsr_msgs/BBox[] bbox

# empty or partial estimate for object IDs 
strands_qsr_msgs/GroupEstimate[] estimate
---
# estimate for all object IDs
strands_qsr_msgs/GroupEstimate[] estimate
